image: node:22

stages:
  - install
  - lint
  - test
  - e2e
  - load
  - mutation
  - sonar
  - terraform
  - ansible
  - build
  - deploy
  - security
  - build_desktop
  - auto_update
  - code_sign
  - distribution
  - docker_build
  - k8s_deploy
  - vps_deploy


workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/
include:
  - local: '.gitlab-ci/01-install.yml'
  - local: '.gitlab-ci/02-lint.yml'
  - local: '.gitlab-ci/03-test.yml'
  - local: '.gitlab-ci/04-e2e.yml'
  - local: '.gitlab-ci/05-load.yml'
  - local: '.gitlab-ci/06-mutation.yml'
  - local: '.gitlab-ci/07-sonar.yml'
  - local: '.gitlab-ci/08-terraform.yml'
  - local: '.gitlab-ci/09-ansible.yml'
  - local: '.gitlab-ci/10-build.yml'
  - local: '.gitlab-ci/11-deploy.yml'
  - local: '.gitlab-ci/12-security.yml'
  - local: '.gitlab-ci/13-build-desktop.yml'
  - local: '.gitlab-ci/14-auto-update.yml'
  - local: '.gitlab-ci/15-code-sign.yml'
  - local: '.gitlab-ci/16-distribution.yml'
  - local: '.gitlab-ci/17-docker-build.yml'
  - local: '.gitlab-ci/18-k8s-deploy.yml'
  - local: '.gitlab-ci/19-vps-deploy.yml'